### ISSUE TITLE
Couldn't open the GOES cloud optical thickness dataset

### ISSUE THREAD

**Issue by 1297299883** [jleinonen/downscaling-rnn-gan#1]
Please give me a new link to down ' open the GOES cloud optical thickness dataset'

**Comment by jleinonen** [comment]
Looks like the Zenodo server where it's hosted is currently down. This is a third-party server so I have no control over it. I'll check it out later to make sure it's working.

**Comment by 1297299883** [comment]
Thank you.I wait ..



---Original---

**Comment by jleinonen** [comment]
This seems to work now. Please check, if it works I'll close the issue.

**Comment by 1297299883** [comment]
Yes，it works.&nbsp;
I have another question. Is this project predicting future precipitation?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jussi Leinonen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月31日(星期天) 凌晨0:03
收件人:&nbsp;"jleinonen/downscaling-rnn-gan"<downscaling-rnn-gan@noreply.github.com&gt;;
抄送:&nbsp;"Leonard"<1297299883@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jleinonen/downscaling-rnn-gaYe] Couldn't open the GOES cloud optical thickness dataset (#1)





 
This seems to work now. Please check, if it works I'll close the issue.
