### ISSUE TITLE
Another question needed your help....

### ISSUE THREAD

**Issue by 1297299883** [jleinonen/downscaling-rnn-gan#4]
Excuse me,please you send me about your  Code Runner Environment.....
Such as  tensorflow  .... version
I want to know how to put the data in folders,so I need to know about project's data folders  structure

**Comment by jleinonen** [comment]
I used TensorFlow 2.0 for all training and evaluation. The data are in single files and they can be specified when calling the training functions or when running the training from command line, so you don't need to have a specific directory structure.

**Comment by jleinonen** [comment]
Closing this since there are no new comments on this issue.
